#ifndef INCLUDED_ARTIFICIALINTELLIGENCE_COMMON_H
#define INCLUDED_ARTIFICIALINTELLIGENCE_COMMON_H

#include <Core/Inc/Core.h>
#include <Math/Inc/QMath.h>

#endif //!INCLUDED_ARTIFICIALINTELLIGENCE_COMMON_H